# Generated by Django 4.2 on 2025-11-28 09:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('pcs', 'Piece'), ('ltr', 'Litre'), ('ml', 'Millilitre')], default='pcs', max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text="Price for 1 base unit (e.g., price per 1 kg if base_unit='kg')", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity available expressed in the base_unit', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='When stock_qty <= this, consider low stock', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.business')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.business')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('business', 'name')},
            },
        ),
    ]
