# Generated by Django 4.2 on 2025-12-02 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_in_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('manual', 'Manual')], max_length=20)),
                ('source_pk', models.IntegerField(blank=True, help_text='PK of source model (PurchaseItem or InvoiceItem)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_txns', to='products.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
