# Generated by Django 4.2 on 2025-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
