# Generated by Django 6.0 on 2025-12-05 11:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_business_options_business_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Owner email (used for login once activated)', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner full name (e.g. John Doe)', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, help_text='Business address'),
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, help_text='Business contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number (if applicable)', max_length=64),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(help_text='Business name', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, help_text='Business phone number', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]*$', 'Enter a valid phone number.')]),
        ),
    ]
