# Generated by Django 6.0 on 2025-12-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_owner_email_business_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner full name ', max_length=255),
        ),
    ]
