# Generated by Django 4.2 on 2025-12-02 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='uom',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=10),
        ),
    ]
