# Generated by Django 4.2 on 2025-12-02 11:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_invoiceitem_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14),
        ),
    ]
