# Generated by Django 6.0 on 2025-12-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('invoice_sequence', models.PositiveIntegerField(default=0, help_text='Monotonic invoice counter for this business')),
            ],
        ),
    ]
