# Generated by Django 6.0 on 2025-12-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
